/* ===== CHAT WIDGET STATE ===== */
/* Tracks whether the embedded chat modal is open */
var _o=false;

// ===== CHAT MODAL TOGGLE =====
// Function: bcT()
// Purpose: Show or hide the embedded Fan Zone chat modal and dismiss the welcome bubble
// Triggers: Click on the floating chat launcher button
function bcT(){document.getElementById('bc-bubble').style.display='none';_o=!_o;document.getElementById('bc-modal').style.display=_o?'block':'none';}

// ===== CHAT MODAL CLOSE =====
// Function: bcC()
// Purpose: Close the embedded Fan Zone chat modal and reset open state
// Triggers: Click on the chat modal close button
function bcC(){_o=false;document.getElementById('bc-modal').style.display='none';}

// ===== CHAT WELCOME TIMER =====
// Function: setTimeout callback
// Purpose: Display the chat welcome bubble after a short delay if chat is not open
// Triggers: Automatic page-load timer
setTimeout(function(){var b=document.getElementById('bc-bubble');if(b&&!_o)b.style.display='block';},3000);

// ===== MENU TAB INTERACTION =====
// Function: tab click event callback
// Purpose: Activate the selected menu category and hide inactive sections
// Triggers: Click on any category tab button
document.querySelectorAll('.tab').forEach(function(t){t.addEventListener('click',function(){document.querySelectorAll('.tab').forEach(function(x){x.classList.remove('active');});document.querySelectorAll('.sec').forEach(function(x){x.classList.remove('active');});t.classList.add('active');var s=document.getElementById('s-'+t.dataset.s);if(s)s.classList.add('active');});});

// ===== MENU CARD TEMPLATE =====
// Function: card(i)
// Purpose: Convert a menu item object into a visible menu card with image, description, and price
// Triggers: Called while rendering full menu and category menu sections
function card(i){var img=i.image?'<img src="'+i.image+'" alt="'+i.name+'" loading="lazy">':'<div class="card-ph">'+i.e+'</div>';var d=i.desc?'<div class="card-d">'+i.desc+'</div>':'<div class="card-d"></div>';var p=i.price?'<div class="card-p">$'+i.price.toFixed(2)+'</div>':'';return'<div class="card">'+img+'<div class="card-b"><div class="card-n">'+i.name+'</div>'+d+p+'</div></div>';}

var S=[{name:'Chicken Tenders',image:'https://krowdimg.b-cdn.net/1062_20250831094650.jpg',desc:'Homemade chicken tenders with a crispy cereal finish, served with crinkle-cut fries.',price:18.75,e:'🍗'},{name:'Borracha Queso Dip',image:'https://krowdimg.b-cdn.net/1062_20250831094804.jpg',desc:'Queso with Anaheim chilis and chorizo, topped with mozzarella and salsa fresca, with warm tortilla chips.',price:17.75,e:'🧀'},{name:'Corn Dogs',image:'https://krowdimg.b-cdn.net/1062_20250831094815.jpg',desc:'Mini chicken corn dogs cooked to a golden brown and piled high with tater tots.',price:15.75,e:'🌭'},{name:'Conan the Bavarian Pretzel',image:'https://krowdimg.b-cdn.net/1062_20250831094826.jpg',desc:'Giant pretzel baked to order with cheese sauce and sweet whole grain mustard.',price:null,e:'🥨'},{name:'Chips, Salsa & Guac',image:'https://krowdimg.b-cdn.net/1062_20250831094837.jpg',desc:'Fresh corn tortilla chips with housemade salsa and guacamole.',price:12.25,e:'🫔'},{name:'Ballpark Nachos',image:'https://krowdimg.b-cdn.net/1062_20250831095038.jpg',desc:'Grilled chicken, ballpark chili, jack & cheddar, pico de gallo, jalapeños, sour cream, guacamole.',price:20.50,e:'🫔'}];
var W=[{name:'Grilled Wings 5pc',image:'https://krowdimg.b-cdn.net/1062_20250831095100.jpg',desc:'Juicy and tender grilled wings.',price:11.50,e:'🍗'},{name:'Grilled Wings 10pc',image:'https://krowdimg.b-cdn.net/1062_20250831095118.jpg',desc:'Juicy and tender grilled wings.',price:21.75,e:'🍗'},{name:'Boneless Wings',image:'https://krowdimg.b-cdn.net/1062_20250831095202.jpg',desc:'Homemade, breaded, and fried to order.',price:16.50,e:'🍗'},{name:'Cali-Flower Wings',image:'https://krowdimg.b-cdn.net/1062_20250831095143.jpg',desc:'Lightly dusted cauliflower florets tossed in your favorite wing sauce.',price:16.75,e:'🥦'},{name:'Garbage Wings',image:'https://krowdimg.b-cdn.net/1062_20250831095238.jpg',desc:'Original flavors with bacon, almonds, blue cheese crumbles, red onion, and sesame seeds.',price:22.75,e:'🍗'},{name:'Russian Roulette Wings',image:'https://krowdimg.b-cdn.net/1062_20250831095254.jpg',desc:'Nine grilled buffalo wings and one really friggin\' spicy bullet.',price:22.75,e:'🔥'}];
var T=[{name:'Tater Skin Tots',image:'https://krowdimg.b-cdn.net/1062_20250831095744.jpg',desc:'Crispy tots smothered with cheddar, pepper jack, bacon, scallions, and sour cream.',price:18.50,e:'🥔'},{name:"Schm'animal Tots",image:'https://krowdimg.b-cdn.net/1062_20250831095756.jpg',desc:'Tots with cheese, caramelized bacon-onions, and homemade Thousand Island.',price:18.50,e:'🥔'},{name:'Buffalo Tots',image:'https://krowdimg.b-cdn.net/1062_20250831095815.jpg',desc:"Frank's Red Hot chicken tenders with cheddar, jalapeño jack, and blue cheese crumbles.",price:18.50,e:'🌶️'},{name:'Nachyo Tots',image:'https://krowdimg.b-cdn.net/1062_20250831095828.jpg',desc:'Tots with tons of cheese, salsa, jalapeños, sour cream, and guacamole.',price:18.50,e:'🥔'},{name:'Pittsburgh Tots',image:'https://krowdimg.b-cdn.net/1062_20250831095845.jpg',desc:'Thinly sliced steak with grilled peppers, mushrooms, onions, swiss and mozzarella.',price:18.50,e:'🥩'},{name:'Archie Tots',image:'https://krowdimg.b-cdn.net/1062_20250831095902.jpg',desc:'Grilled chicken, mushrooms, swiss & mozzarella cheese, with Archie sauce.',price:18.50,e:'🍄'}];
var SA=[{name:'Kale, Brussels & Broccoli Salad',image:'https://krowdimg.b-cdn.net/1062_20250831095919.jpg',desc:'Kale, brussels sprouts, shaved broccoli, walnuts, strawberries, parmesan in sherry-shallot vinaigrette.',price:14.50,e:'🥗'},{name:'BBQ Cilantro Chicken Salad',image:'https://krowdimg.b-cdn.net/1062_20250831095932.jpg',desc:'Grilled BBQ chicken on mixed greens with bell peppers, cucumbers, mozzarella, cilantro, avocado.',price:19.50,e:'🥗'},{name:'Asian Chopped Chicken Salad',image:'https://krowdimg.b-cdn.net/1062_20250831095950.jpg',desc:'Romaine, Napa cabbage, carrots, mint, cilantro, grapes, almonds, crispy wontons with Hoisin-lime dressing.',price:19.50,e:'🥗'},{name:"Jimmy's Chicken Caesar",image:'https://krowdimg.b-cdn.net/1062_20250831100004.jpg',desc:'Chicken and romaine tossed in housemade caesar dressing with parmesan and croutons.',price:19.50,e:'🥗'},{name:'Padres Power Bowl',image:'https://krowdimg.b-cdn.net/1062_20250831100032.jpg',desc:'Quinoa with black beans, avocado, tomatoes, green onions, gruyere cheese, broccoli, lime vinaigrette.',price:13.75,e:'🥗'},{name:'The Marvin Cobb',image:'https://krowdimg.b-cdn.net/1062_20250831100053.jpg',desc:'Mixed greens with grilled chicken, bacon, avocado, red onion, tomato, blue cheese crumbles, egg.',price:19.50,e:'🥗'}];
var SO=[{name:'Chili Cup',image:'https://krowdimg.b-cdn.net/1062_20250831100111.jpg',desc:'',price:7.50,e:'🍲'},{name:'Chili Bowl',image:'https://krowdimg.b-cdn.net/1062_20250831100122.jpg',desc:'',price:9.50,e:'🍲'},{name:'Tomato Bisque Cup',image:'https://krowdimg.b-cdn.net/1062_20250831100150.jpg',desc:'',price:7.50,e:'🍅'},{name:'Tomato Bisque Bowl',image:'https://krowdimg.b-cdn.net/1062_20250831100156.jpg',desc:'',price:9.50,e:'🍅'}];
var B=[{name:'The Woody Burger',image:'https://krowdimg.b-cdn.net/1062_20250831100353.jpg',desc:'Classic 1/2 lb. burger with cheese, lettuce, tomato, onion, and tots.',price:19.50,e:'🍔'},{name:'Black & Blue',image:'https://krowdimg.b-cdn.net/1062_20250831100410.jpg',desc:'The Woody with house-blend blackening spices, lettuce, tomato, onion, and blue cheese.',price:20.50,e:'🍔'},{name:'Carolina Gold',image:'https://krowdimg.b-cdn.net/1062_20250831100433.jpg',desc:'The Woody with cheese, bacon, lettuce, tomato, onion, and Carolina Gold BBQ sauce.',price:21.50,e:'🍔'},{name:'Good Egg & Bacon',image:'https://krowdimg.b-cdn.net/1062_20250831100449.jpg',desc:'The Woody topped with a fried egg, bacon, cheese, lettuce, tomato, onion.',price:20.50,e:'🍳'},{name:"Schm'animal Style",image:'https://krowdimg.b-cdn.net/1062_20250831100515.jpg',desc:'The Woody with cheese, secret sauce, caramelized bacon-onions, lettuce, tomato, pickles.',price:21.50,e:'🍔'},{name:'Fresh Grind Turkey Burger',image:'https://krowdimg.b-cdn.net/1062_20250831100530.jpg',desc:'Housemade turkey burger with rosemary, thyme, chipotle aioli, and your choice of cheese.',price:20.50,e:'🦃'},{name:'Mushroom & Swiss',image:'https://krowdimg.b-cdn.net/1062_20250831100550.jpg',desc:'The Woody covered with sautéed mushrooms, swiss cheese, lettuce, tomato, onion.',price:20.50,e:'🍄'}];
var SW=[{name:'The Archie Chicken',image:'https://krowdimg.b-cdn.net/1062_20250831100622.jpg',desc:'Grilled chicken with mushrooms, chipotle aioli, swiss & mozzarella, and Archie Sauce.',price:18.75,e:'🥪'},{name:'The French Dip',image:'https://krowdimg.b-cdn.net/1062_20250831100635.jpg',desc:'Shaved steak with Swiss cheese and creamy horseradish on a French roll with au jus.',price:20.50,e:'🥪'},{name:'The Pittsburgh Steak',image:'https://krowdimg.b-cdn.net/1062_20250831100659.jpg',desc:'Thinly sliced steak, cheese, and chipotle aioli.',price:19.50,e:'🥩'},{name:'The Patrick Melt',image:'https://krowdimg.b-cdn.net/1062_20250831100730.jpg',desc:"Thinly sliced grilled pastrami on toasted sourdough with swiss cheese and chipotle aioli.",price:19.50,e:'🥪'},{name:'The Southwestern Chicken',image:'https://krowdimg.b-cdn.net/1062_20250831100749.jpg',desc:'Fresh grilled chicken with pepper jack, guacamole, chipotle aioli, and grilled Anaheim chiles.',price:19.50,e:'🌶️'},{name:'Grilled Cheesy Sourdough',image:'https://krowdimg.b-cdn.net/1062_20250831100830.jpg',desc:'With gruyere & cheddar cheese.',price:14.50,e:'🧀'},{name:'Chicken Caesar Wrap',image:'https://krowdimg.b-cdn.net/1062_20250831100850.jpg',desc:"Grilled chicken, spicy Caesar dressing, shredded romaine, parmesan cheese, chipotle aioli.",price:19.50,e:'🥪'}];
var E=[{name:'Steakums',image:'https://krowdimg.b-cdn.net/1062_20250831100909.jpg',desc:'Classic Steakums served "All the Way" with grilled peppers, mushrooms, and onions.',price:27.50,e:'🥩'},{name:'Montreal Steakums',image:'https://krowdimg.b-cdn.net/1062_20250831100944.jpg',desc:'Flame-grilled steak with Montreal seasoning and garlic butter served with garlic bread.',price:30.50,e:'🥩'},{name:'Black & Blue Steakums',image:'https://krowdimg.b-cdn.net/1062_20250831101037.jpg',desc:'Steakums with blackening spice and blue cheese crumbles served with garlic bread.',price:30.50,e:'🔵'},{name:'Fish Fry & Chips',image:'https://krowdimg.b-cdn.net/1062_20250831100923.jpg',desc:'Featured market fish lightly crusted in seasoned mix, served with crinkle-cut fries and tartar sauce.',price:21.75,e:'🐟'},{name:'Fish Tacos',image:'https://krowdimg.b-cdn.net/1062_20250831101001.jpg',desc:"Your choice of Bub's Fish Fry or grilled fish with lime crema, pico de gallo, and cabbage.",price:18.75,e:'🌮'},{name:"Mac 'N Cheese",image:'https://krowdimg.b-cdn.net/1062_20250831101050.jpg',desc:'Classic cheddar mac. Add chicken +$7, burger +$8, shrimp/steak +$9.',price:14.75,e:'🧀'}];
var SI=[{name:'Regular Tater Tots',image:'https://krowdimg.b-cdn.net/1062_20250831095016.jpg',desc:'',price:7.75,e:'🥔'},{name:'Crinkle Cut Fries',image:'https://krowdimg.b-cdn.net/1062_20250831095018.jpg',desc:'',price:7.75,e:'🍟'},{name:'Onion Rings',image:'https://krowdimg.b-cdn.net/1062_20250831095021.jpg',desc:'',price:9.75,e:'🧅'},{name:'Sweet Potato Tots',image:'https://krowdimg.b-cdn.net/1062_20250831095027.jpg',desc:'',price:9.25,e:'🍠'}];
var GRPS=[['🧅 Starters',S],['🍗 Wings',W],['🥔 Loaded Tots',T],['🥗 Salads & Bowls',SA],['🍲 Soup & Chili',SO],['🍔 Burgers',B],['🥪 Sandwiches',SW],['🍽️ Entrees',E],['🍟 Sides',SI]];
var SECS=[['starters','🧅 Starters',S],['wings','🍗 Wings',W],['tots','🥔 Loaded Tots',T],['salads','🥗 Salads & Bowls',SA],['soup','🍲 Soup & Chili',SO],['burgers','🍔 Burgers',B],['sandwiches','🥪 Sandwiches',SW],['entrees','🍽️ Entrees',E],['sides','🍟 Sides',SI]];

// ===== MENU RENDERING =====
// Function: dynamic render block
// Purpose: Build the full menu panel and each category-specific panel from structured menu arrays
// Triggers: Runs immediately after menu data is defined
var html='<div class="sec active" id="s-all"><div class="sec-h">🍽️ Full Menu</div>';
GRPS.forEach(function(g){html+='<div class="grp"><div class="grp-t">'+g[0]+'</div><div class="grid">';g[1].forEach(function(i){html+=card(i);});html+='</div></div>';});html+='</div>';
SECS.forEach(function(s){html+='<div class="sec" id="s-'+s[0]+'"><div class="sec-h">'+s[1]+'</div><div class="grid">';s[2].forEach(function(i){html+=card(i);});html+='</div></div>';});
document.getElementById('menuWrap').innerHTML=html;